export const iconsData = [
	{
		categoryName: 'Actions',
		icons: [
			'plus-outline',
			'minus-outline',
			'x-outline',
			'plus-circle-outline',
			'minus-circle-outline',
			'x-circle-outline',
			'block-outline',
			'power-outline',
			'printer-outline',
			'bookmark-outline',
			'trash-outline',
			'search-outline',
			'upload-outline',
			'download-outline',
			'edit-outline',
			'copy-outline',
			'tag-outline',
			'bullseye-outline',
			'scope-outline',
			'lifebuoy-outline',
			'trophy-outline',
			'loop-outline',
		],
	},
	{
		categoryName: 'Files & documents',
		icons: [
			'document-outline',
			'document-text-outline',
			'document-texts-outline',
			'clipboard-outline',
			'clipboard-text-outline',
			'folder-outline',
			'folder-open-outline',
			'briefcase-outline',
			'layers-outline',
			'subtask-outline',
			'box-outline',
			'package-outline',
			'attachment-clip-outline',
			'link-outline',
			'upload-cloud-outline',
			'download-cloud-outline',
		],
	},
	{
		categoryName: 'Notifications',
		icons: [
			'notification-bell-outline',
			'notification-bell-timer-outline',
			'alert-outline',
			'check-circle-outline',
			'check-outline',
			'info-outline',
			'help-outline',
			'warning-outline',
			'mail-outline',
			'checkbox-checked-outlined',
			'flag-outline',
			'sparks-outline',
			'lamp-outline',
			'lamp-on-outline',
		],
	},
	{
		categoryName: 'Menu & navigation',
		icons: [
			'home-outline',
			'dashboard-outline',
			'grid-outline',
			'list-outline',
			'menu-outline',
			'filter-outline',
			'more-horizontal-outline',
			'more-vertical-outline',
			'reorder-outline',
			'sidebar-expand-outline',
			'sidebar-collapse-outline',
		],
	},
	{
		categoryName: 'Arrows',
		icons: [
			'arrow-up-circle-outline',
			'arrow-down-circle-outline',
			'arrow-right-circle-outline',
			'arrow-left-circle-outline',
			'caret-up-outline',
			'caret-down-outline',
			'caret-right-outline',
			'caret-left-outline',
			'open-in-new-tab-outline',
			'logout-outline',
			'login-outline',
			'rotate-left-outline',
			'rotate-right-outline',
			'loading-right-outline',
			'loading-left-outline',
			'refresh-outline',
			'arrow-left-outline',
			'arrow-up-outline',
			'arrow-right-outline',
			'arrow-down-outline',
			'swap-horizontal-arrows-outline',
			'swap-vertical-arrows-outline',
			'sort-ascending-duotone',
			'sort-descending-duotone',
			'expand-outline',
			'minimize-outline',
			'move-outline',
			'undo-outline',
			'rendo-outline',
			'shuffle-outline',
			'unfold-vertical-outline',
			'unfold-horizontal-outline',
		],
	},
	{
		categoryName: 'Multimedia',
		icons: [
			'translate-outline',
			'play-outline',
			'pause-outline',
			'play-circle-outline',
			'pause-circle-outline',
			'stop-circle-outline',
			'image-outline',
			'videocam-outline',
			'bolt-outline',
			'open-book-outline',
			'mouse-outline',
			'monitor-outline',
			'tv-outline',
			'totem-outline',
			'volume-1-outline',
			'volume-2-outline',
			'phone-outline',
			'share-outline',
			'headphone-outline',
			'headset-outline',
		],
	},
	{
		categoryName: 'Users',
		icons: [
			'user-outline',
			'user-remove-outline',
			'user-add-outline',
			'users-outline',
		],
	},
	{
		categoryName: 'Charts',
		icons: [
			'trending-up-outline',
			'trending-down-outline',
			'pie-chart-outline',
			'chart-column-outline',
		],
	},
	{
		categoryName: 'Settings',
		icons: ['settings-outline', 'funnel-outline', 'sliders-outline'],
	},
	{
		categoryName: 'Location',
		icons: [
			'map-pin-outline',
			'map-outline',
			'pin-outline',
			'bed-outiline',
			'building-outline',
			'ticket-outline',
			'moon-outline',
			'sun-outline',
		],
	},
	{
		categoryName: 'Date & time',
		icons: [
			'calendar-clear-outline',
			'calendar-outline',
			'clock-outline',
			'history-outline',
		],
	},
	{
		categoryName: 'Security',
		icons: [
			'visibility-on-outline',
			'visibility-off-outline',
			'lock-outline',
			'unlock-outline',
			'key-outline',
			'shield-outline',
			'shield-tick-outline',
			'shield-alert-outline',
			'radar-outline',
		],
	},
	{
		categoryName: 'Social',
		icons: [
			'chatbubble-outline', 
			'chatbubbles-outline',
			'trophy-outline',
			'weight-outline',
			'fire-outline',
			'star-outline',
		],
	},
	{
		categoryName: 'Brands',
		icons: [
			'github-logo-outline',
			'gitlab-logo-outline',
			'figma-logo-outline',
			'framer-logo-outline',
		],
	},
	{
		categoryName: 'Health',
		icons: [
			'medicine-outline',
			'test-tube-outline',
			'syringe-outline',
			'tube-outline',
			'sample-container-outline',
			'stethoscope-outline',
			'heart-rate-outline',
			'ambulance-outline',
		],
	},
];
