export const PALETE = [
  {
    name: "Piccolo Green",
    tokens: [
      "$gp-50",
      "$gp-100",
      "$gp-200",
      "$gp-300",
      "$gp-400",
      "$gp-500",
      "$gp-600",
      "$gp-700",
    ],
    hex: ["#FFFFFF"],
    isADarkColor: false,
  },
  {
    name: "Sulivan Turquoise",
    tokens: [
      "$ts-50",
      "$ts-100",
      "$ts-200",
      "$ts-300",
      "$ts-400",
      "$ts-500",
      "$ts-600",
      "$ts-700",
    ],
    hex: ["#FFFFFF"],
    isADarkColor: false,
  },
  {
    name: "Nocturne Blue",
    tokens: [
      "$bn-50",
      "$bn-100",
      "$bn-200",
      "$bn-300",
      "$bn-400",
      "$bn-500",
      "$bn-600",
      "$bn-700",
    ],
    hex: ["#FFFFFF"],
    isADarkColor: false,
  },
  {
    name: "NightWing Indigo",
    tokens: [
      "$in-50",
      "$in-100",
      "$in-200",
      "$in-300",
      "$in-400",
      "$in-500",
      "$in-600",
      "$in-700",
    ],
    hex: ["#FFFFFF"],
    isADarkColor: false,
  },
  {
    name: "Raven Violet",
    tokens: [
      "$vr-50",
      "$vr-100",
      "$vr-200",
      "$vr-300",
      "$vr-400",
      "$vr-500",
      "$vr-600",
      "$vr-700",
    ],
    hex: ["#FFFFFF"],
    isADarkColor: false,
  },
  {
    name: "Peppa Pink",
    tokens: [
      "$pp-50",
      "$pp-100",
      "$pp-200",
      "$pp-300",
      "$pp-400",
      "$pp-500",
      "$pp-600",
      "$pp-700",
    ],
    hex: ["#FFFFFF"],
    isADarkColor: false,
  },
  {
    name: "Carmen Red",
    tokens: [
      "$rc-50",
      "$rc-100",
      "$rc-200",
      "$rc-300",
      "$rc-400",
      "$rc-500",
      "$rc-600",
      "$rc-700",
    ],
    hex: ["#FFFFFF"],
    isADarkColor: false,
  },
  {
    name: "Goku Orange",
    tokens: [
      "$og-50",
      "$og-100",
      "$og-200",
      "$og-300",
      "$og-400",
      "$og-500",
      "$og-600",
      "$og-700",
    ],
    hex: ["#FFFFFF"],
    isADarkColor: false,
  },
  {
    name: "Lisa Amber",
    tokens: [
      "$al-50",
      "$al-100",
      "$al-200",
      "$al-300",
      "$al-400",
      "$al-500",
      "$al-600",
      "$al-700",
    ],
    hex: ["#FFFFFF"],
    isADarkColor: false,
  },
  {
    name: "Light Neutrals",
    tokens: ["$n-0", "$n-10", "$n-20", "$n-30", "$n-40"],
    isADarkColor: false,
  },
  {
    name: "Mid Neutrals",
    tokens: ["$n-50", "$n-100", "$n-200", "$n-300", "$n-400"],
    isADarkColor: false,
  },
  {
    name: "Dark Neutrals",
    tokens: ["$n-500", "$n-600", "$n-700", "$n-800", "$n-900"],
    isADarkColor: true,
  },
];
