'🧱 Componente':
- changed-files:
  - any-glob-to-any-file: ['src/components/index.ts']

'🐛 Bug':
- changed-files:
  - any-glob-to-any-file: ['src/components/*.vue']
  - all-globs-to-all-files: ['!src/stories/**']

'📃 Documentação':
- changed-files:
  - any-glob-to-any-file: ['src/stories/**/*.stories.mdx']
  - all-globs-to-all-files: ['!src/components/index.ts', '!src/components/*.vue']

'🛠️ Build':
- changed-files:
  - any-glob-to-any-file: ['vite.config.ts', 'src/components/index.ts', '.github/**/*']

'🧩 Token':
- changed-files:
  - any-glob-to-any-file: ['src/assets/sass/**/*', 'src/stories/tokens/*.stories.mdx']
