import ActionsList from './ActionsList.vue';
import Alert from './Alert.vue';
import AlertCard from './AlertCard.vue';
import Badge from './Badge.vue';
import Button from './Button.vue';
import CalloutCard from './CalloutCard.vue';
import CarouselController from './CarouselController.vue';
import Checkbox from './Checkbox.vue';
import ClusteredMultiselect from './ClusteredMultiselect.vue';
import CollapsibleContainer from './CollapsibleContainer.vue';
import DashboardCard from './DashboardCard.vue';
import DropDown from './DropDown.vue';
import EmptyState from './EmptyState.vue';
import ExpansionCard from './ExpansionCard.vue';
import Highlight from './Highlight.vue';
import IconButton from './IconButton.vue';
import InnerTabs from './InnerTabs.vue';
import Link from './Link.vue';
import Loader from './Loader.vue';
import LoadingBar from './LoadingBar.vue';
import NavBar from './NavBar.vue';
import PanelCard from './PanelCard.vue';
import Popover from './Popover.vue';
import ProgressBar from './ProgressBar.vue';
import ProgressCircular from './ProgressCircular.vue';
import Radio from './Radio.vue';
import RadioButtonGroup from './RadioButtonGroup.vue';
import Scrollable from './Scrollable.vue';
import Select from './Select.vue';
import SideSheet from './SideSheet.vue';
import SkeletonText from './SkeletonText.vue';
import Slider from './Slider.vue';
import Spinner from './Spinner.vue';
import Stepper from './Stepper.vue';
import StepperInput from './StepperInput.vue';
import Table from './Table.vue';
import Tabs from './Tabs.vue';
import TextInput from './TextInput.vue';
import TimeInput from './TimeInput.vue';
import Timeline from './Timeline.vue';
import ToggleSwitch from './ToggleSwitch.vue';
import Tooltip from './Tooltip.vue';
import UploadInput from './UploadInput.vue';


export default {
	install: (app: any, options: any) => {
		app.component('CdsActionsList', ActionsList);
		app.component('CdsAlert', Alert);
		app.component('CdsAlertCard', AlertCard);
		app.component('CdsBadge', Badge);
		app.component('CdsButton', Button);
		app.component('CdsCalloutCard', CalloutCard);
		app.component('CdsCarouselController', CarouselController);
		app.component('CdsCheckbox', Checkbox);
		app.component('CdsClusteredMultiselect', ClusteredMultiselect);
		app.component('CdsCollapsibleContainer', CollapsibleContainer);
		app.component('CdsDashboardCard', DashboardCard);
		app.component('CdsDropDown', DropDown);
		app.component('CdsEmptyState', EmptyState);
		app.component('CdsExpansionCard', ExpansionCard);
		app.component('CdsHighlight', Highlight);
		app.component('CdsIconButton', IconButton);
		app.component('CdsInnerTabs', InnerTabs);
		app.component('CdsLink', Link);
		app.component('CdsLoader', Loader);
		app.component('CdsLoadingBar', LoadingBar);
		app.component('CdsNavBar', NavBar);
		app.component('CdsPanelCard', PanelCard);
		app.component('CdsPopover', Popover);
		app.component('CdsProgressBar', ProgressBar);
		app.component('CdsProgressCircular', ProgressCircular);
		app.component('CdsRadio', Radio);
		app.component('CdsRadioButtonGroup', RadioButtonGroup);
		app.component('CdsScrollable', Scrollable);
		app.component('CdsSelect', Select);
		app.component('CdsSideSheet', SideSheet);
		app.component('CdsSkeletonText', SkeletonText);
		app.component('CdsSlider', Slider);
		app.component('CdsSpinner', Spinner);
		app.component('CdsStepper', Stepper);
		app.component('CdsStepperInput', StepperInput);
		app.component('CdsTable', Table);
		app.component('CdsTabs', Tabs);
		app.component('CdsTextInput', TextInput);
		app.component('CdsTimeInput', TimeInput);
		app.component('CdsTimeline', Timeline);
		app.component('CdsToggleSwitch', ToggleSwitch);
		app.component('CdsTooltip', Tooltip);
		app.component('CdsUploadInput', UploadInput);
	},
}
