name: "Deployer 🚀"

on: 
  push:
    branches:
      - main

jobs:
  docs-deployment:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 🟢 Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: 🔧 Install dependencies
        run: |
          npm cache clean --force
          npm install
      
      - name: 📖 Build docs
        run: npm run docs:build

      - name: 🚀 Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vitepress/dist
          branch: gh-pages
