name: "Publisher Next 📦 (next branch)"

on:
  push:
    branches:
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm ci && npm run build
      - name: Bump version to next
        run: |
          npm version prerelease --preid=next
          git push origin next --follow-tags
      - name: Publish next version on NPM 📦
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
